wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: valid_loss
      5: 1
      6:
      - 1
    - 1: accuracy
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    python_version: 3.8.11
    start_time: 1642587588
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      2:
      - 1
      - 5
      - 9
      - 11
      3:
      - 7
      - 16
      4: 3.8.11
      5: 0.12.9
      6: 4.15.0
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.0005
lr:
  desc: null
  value: 0.0005
model:
  desc: null
  value: "ImdbTransformer(\n  (model): BertForSequenceClassification(\n    (bert):\
    \ BertModel(\n      (embeddings): BertEmbeddings(\n        (word_embeddings):\
    \ Embedding(28996, 768, padding_idx=0)\n        (position_embeddings): Embedding(512,\
    \ 768)\n        (token_type_embeddings): Embedding(2, 768)\n        (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n        (dropout): Dropout(p=0.1,\
    \ inplace=False)\n      )\n      (encoder): BertEncoder(\n        (layer): ModuleList(\n\
    \          (0): BertLayer(\n            (attention): BertAttention(\n        \
    \      (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (1): BertLayer(\n            (attention): BertAttention(\n        \
    \      (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (2): BertLayer(\n            (attention): BertAttention(\n        \
    \      (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (3): BertLayer(\n            (attention): BertAttention(\n        \
    \      (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (4): BertLayer(\n            (attention): BertAttention(\n        \
    \      (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (5): BertLayer(\n            (attention): BertAttention(\n        \
    \      (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (6): BertLayer(\n            (attention): BertAttention(\n        \
    \      (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (7): BertLayer(\n            (attention): BertAttention(\n        \
    \      (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (8): BertLayer(\n            (attention): BertAttention(\n        \
    \      (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (9): BertLayer(\n            (attention): BertAttention(\n        \
    \      (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (10): BertLayer(\n            (attention): BertAttention(\n       \
    \       (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \          (11): BertLayer(\n            (attention): BertAttention(\n       \
    \       (self): BertSelfAttention(\n                (query): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (key): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (value): Linear(in_features=768,\
    \ out_features=768, bias=True)\n                (dropout): Dropout(p=0.1, inplace=False)\n\
    \              )\n              (output): BertSelfOutput(\n                (dense):\
    \ Linear(in_features=768, out_features=768, bias=True)\n                (LayerNorm):\
    \ LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n                (dropout):\
    \ Dropout(p=0.1, inplace=False)\n              )\n            )\n            (intermediate):\
    \ BertIntermediate(\n              (dense): Linear(in_features=768, out_features=3072,\
    \ bias=True)\n            )\n            (output): BertOutput(\n             \
    \ (dense): Linear(in_features=3072, out_features=768, bias=True)\n           \
    \   (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)\n     \
    \         (dropout): Dropout(p=0.1, inplace=False)\n            )\n          )\n\
    \        )\n      )\n      (pooler): BertPooler(\n        (dense): Linear(in_features=768,\
    \ out_features=768, bias=True)\n        (activation): Tanh()\n      )\n    )\n\
    \    (dropout): Dropout(p=0.1, inplace=False)\n    (classifier): Linear(in_features=768,\
    \ out_features=2, bias=True)\n  )\n)"
model_name:
  desc: null
  value: bert-base-cased
seed:
  desc: null
  value: 42
