 name: CML Evaluation
 on: [push]
 jobs:
   run:
     runs-on: [ubuntu-latest]
     container: docker://iterativeai/cml:0-dvc2-base1  # continuous machine learning tools
     steps:
         - uses: actions/checkout@v2
         - name: cml_eval
           env:
               REPO_TOKEN: $
           run: |
               pip install -r requirements.txt  # install dependencies
               python exercises/s5/CML_eval.py  # run training

               # send all information to report.md that will be reported to us when the workflow finish
               cat exercises/s6/classification_report.txt >> report.md
               cml-publish exercises/s6/confusion_matrix.png --md >> report.md
               cml-send-comment report.md
